name: Deploy Golang Groups Relay

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clean up previous builds
        run: rm -rf examples/groups.nip29.com/groups.nip29.com

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'  # Use latest Go version

      - name: Cache Go Modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build Application
        run: |
          cd examples/groups.nip29.com
          GOOS=linux GOARCH=arm64 go build -buildvcs=false -o groups.nip29.com

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: relay-server
          path: examples/groups.nip29.com/groups.nip29.com

  deploy:
    runs-on: ubuntu-24.04
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: relay-server

      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "groups.nip29.com"
          target: "/var/www/relays"

      - name: Set execute permission
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: chmod +x /var/www/relays/groups.nip29.com

      - name: Restart Application
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: sudo systemctl restart relay-groups.service
